services:
  - type: web
    name: barbachli-api
    env: node
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        value: 12345
        # Remplacez par votre propre secret JWT en production
      - key: SUPABASE_URL
        value: https://iptgkvofawoqvykmkcrk.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwdGdrdm9mYXdvcXZ5a21rY3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjkxMTMsImV4cCI6MjA2NDQ0NTExM30.oUsFpKGgeddXRU5lbaeaufBZ2wV7rnl1a0h2YEfC9b8
      - key: RENDER
        value: "true"
      - key: REACT_APP_API_URL
        value: https://barbachli-api.onrender.com/api 