services:
  - type: web
    name: barbachli-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        value: 12345
        # Remplacez par votre propre secret JWT en production
      - key: DATABASE_URL
        value: postgres://postgres.iptgkvofawoqvykmkcrk:Gaston.07730218@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
        # Connection pooler URL for better compatibility with IPv4
      - key: PGSSLMODE
        value: "no-verify"
      - key: REACT_APP_API_URL
        value: https://barbachli-api.onrender.com/api 