import React from 'react';
import * as ReactIcons from 'react-icons/fa';
import * as FiIcons from 'react-icons/fi';
import { IconBaseProps } from 'react-icons';

// Create a wrapper component for each icon to avoid TypeScript errors
export const FaIcons = {
  // Dashboard icons
  FaHome: (props: IconBaseProps = {}) => <span><ReactIcons.FaHome {...props} /></span>,
  FaUsers: (props: IconBaseProps = {}) => <span><ReactIcons.FaUsers {...props} /></span>,
  FaShoppingCart: (props: IconBaseProps = {}) => <span><ReactIcons.FaShoppingCart {...props} /></span>,
  FaBox: (props: IconBaseProps = {}) => <span><ReactIcons.FaBox {...props} /></span>,
  FaStar: (props: IconBaseProps = {}) => <span><ReactIcons.FaStar {...props} /></span>,
  FaStarHalfAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaStarHalfAlt {...props} /></span>,
  FaRegStar: (props: IconBaseProps = {}) => <span><ReactIcons.FaRegStar {...props} /></span>,
  FaTag: (props: IconBaseProps = {}) => <span><ReactIcons.FaTag {...props} /></span>,
  FaTags: (props: IconBaseProps = {}) => <span><ReactIcons.FaTags {...props} /></span>,
  FaChartBar: (props: IconBaseProps = {}) => <span><ReactIcons.FaChartBar {...props} /></span>,
  FaCog: (props: IconBaseProps = {}) => <span><ReactIcons.FaCog {...props} /></span>,
  FaSignOutAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaSignOutAlt {...props} /></span>,
  FaBars: (props: IconBaseProps = {}) => <span><ReactIcons.FaBars {...props} /></span>,
  FaSearch: (props: IconBaseProps = {}) => <span><ReactIcons.FaSearch {...props} /></span>,
  FaBell: (props: IconBaseProps = {}) => <span><ReactIcons.FaBell {...props} /></span>,
  FaCalendarAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaCalendarAlt {...props} /></span>,
  FaEnvelope: (props: IconBaseProps = {}) => <span><ReactIcons.FaEnvelope {...props} /></span>,
  FaUser: (props: IconBaseProps = {}) => <span><ReactIcons.FaUser {...props} /></span>,
  FaUserPlus: (props: IconBaseProps = {}) => <span><ReactIcons.FaUserPlus {...props} /></span>,
  FaUserEdit: (props: IconBaseProps = {}) => <span><ReactIcons.FaUserEdit {...props} /></span>,
  FaUserCog: (props: IconBaseProps = {}) => <span><ReactIcons.FaUserCog {...props} /></span>,
  FaUserShield: (props: IconBaseProps = {}) => <span><ReactIcons.FaUserShield {...props} /></span>,
  FaEdit: (props: IconBaseProps = {}) => <span><ReactIcons.FaEdit {...props} /></span>,
  FaTrashAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaTrashAlt {...props} /></span>,
  FaPlus: (props: IconBaseProps = {}) => <span><ReactIcons.FaPlus {...props} /></span>,
  FaMinus: (props: IconBaseProps = {}) => <span><ReactIcons.FaMinus {...props} /></span>,
  FaSave: (props: IconBaseProps = {}) => <span><ReactIcons.FaSave {...props} /></span>,
  FaTimes: (props: IconBaseProps = {}) => <span><ReactIcons.FaTimes {...props} /></span>,
  FaCheck: (props: IconBaseProps = {}) => <span><ReactIcons.FaCheck {...props} /></span>,
  FaEye: (props: IconBaseProps = {}) => <span><ReactIcons.FaEye {...props} /></span>,
  FaEyeSlash: (props: IconBaseProps = {}) => <span><ReactIcons.FaEyeSlash {...props} /></span>,
  FaShoppingBag: (props: IconBaseProps = {}) => <span><ReactIcons.FaShoppingBag {...props} /></span>,
  FaMoneyBillWave: (props: IconBaseProps = {}) => <span><ReactIcons.FaMoneyBillWave {...props} /></span>,
  FaCreditCard: (props: IconBaseProps = {}) => <span><ReactIcons.FaCreditCard {...props} /></span>,
  FaImage: (props: IconBaseProps = {}) => <span><ReactIcons.FaImage {...props} /></span>,
  FaImages: (props: IconBaseProps = {}) => <span><ReactIcons.FaImages {...props} /></span>,
  FaUpload: (props: IconBaseProps = {}) => <span><ReactIcons.FaUpload {...props} /></span>,
  FaDownload: (props: IconBaseProps = {}) => <span><ReactIcons.FaDownload {...props} /></span>,
  FaCloudUploadAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaCloudUploadAlt {...props} /></span>,
  FaCloudDownloadAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaCloudDownloadAlt {...props} /></span>,
  FaFile: (props: IconBaseProps = {}) => <span><ReactIcons.FaFile {...props} /></span>,
  FaFileAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaFileAlt {...props} /></span>,
  FaFileImage: (props: IconBaseProps = {}) => <span><ReactIcons.FaFileImage {...props} /></span>,
  FaFilePdf: (props: IconBaseProps = {}) => <span><ReactIcons.FaFilePdf {...props} /></span>,
  FaFileExcel: (props: IconBaseProps = {}) => <span><ReactIcons.FaFileExcel {...props} /></span>,
  FaFileWord: (props: IconBaseProps = {}) => <span><ReactIcons.FaFileWord {...props} /></span>,
  FaFileCsv: (props: IconBaseProps = {}) => <span><ReactIcons.FaFileCsv {...props} /></span>,
  FaFileArchive: (props: IconBaseProps = {}) => <span><ReactIcons.FaFileArchive {...props} /></span>,
  FaLink: (props: IconBaseProps = {}) => <span><ReactIcons.FaLink {...props} /></span>,
  FaExternalLinkAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaExternalLinkAlt {...props} /></span>,
  FaShareAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaShareAlt {...props} /></span>,
  FaInfoCircle: (props: IconBaseProps = {}) => <span><ReactIcons.FaInfoCircle {...props} /></span>,
  FaQuestionCircle: (props: IconBaseProps = {}) => <span><ReactIcons.FaQuestionCircle {...props} /></span>,
  FaExclamationCircle: (props: IconBaseProps = {}) => <span><ReactIcons.FaExclamationCircle {...props} /></span>,
  FaExclamationTriangle: (props: IconBaseProps = {}) => <span><ReactIcons.FaExclamationTriangle {...props} /></span>,
  FaCheckCircle: (props: IconBaseProps = {}) => <span><ReactIcons.FaCheckCircle {...props} /></span>,
  FaTimesCircle: (props: IconBaseProps = {}) => <span><ReactIcons.FaTimesCircle {...props} /></span>,
  FaSort: (props: IconBaseProps = {}) => <span><ReactIcons.FaSort {...props} /></span>,
  FaSortUp: (props: IconBaseProps = {}) => <span><ReactIcons.FaSortUp {...props} /></span>,
  FaSortDown: (props: IconBaseProps = {}) => <span><ReactIcons.FaSortDown {...props} /></span>,
  FaRegHeart: (props: IconBaseProps = {}) => <span><ReactIcons.FaRegHeart {...props} /></span>,
  FaHeart: (props: IconBaseProps = {}) => <span><ReactIcons.FaHeart {...props} /></span>,
  FaMapMarkerAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaMapMarkerAlt {...props} /></span>,
  FaPhoneAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaPhoneAlt {...props} /></span>,
  FaGlobe: (props: IconBaseProps = {}) => <span><ReactIcons.FaGlobe {...props} /></span>,
  FaGlobeAmericas: (props: IconBaseProps = {}) => <span><ReactIcons.FaGlobeAmericas {...props} /></span>,
  FaLock: (props: IconBaseProps = {}) => <span><ReactIcons.FaLock {...props} /></span>,
  FaUnlock: (props: IconBaseProps = {}) => <span><ReactIcons.FaUnlock {...props} /></span>,
  FaLockOpen: (props: IconBaseProps = {}) => <span><ReactIcons.FaLockOpen {...props} /></span>,
  FaShieldAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaShieldAlt {...props} /></span>,
  FaTruck: (props: IconBaseProps = {}) => <span><ReactIcons.FaTruck {...props} /></span>,
  FaShippingFast: (props: IconBaseProps = {}) => <span><ReactIcons.FaShippingFast {...props} /></span>,
  FaAngleDown: (props: IconBaseProps = {}) => <span><ReactIcons.FaAngleDown {...props} /></span>,
  FaAngleUp: (props: IconBaseProps = {}) => <span><ReactIcons.FaAngleUp {...props} /></span>,
  FaCommentSlash: (props: IconBaseProps = {}) => <span><ReactIcons.FaCommentSlash {...props} /></span>,
  FaPencilAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaPencilAlt {...props} /></span>,
  FaRegClock: (props: IconBaseProps = {}) => <span><ReactIcons.FaRegClock {...props} /></span>,
  FaBoxOpen: (props: IconBaseProps = {}) => <span><ReactIcons.FaBoxOpen {...props} /></span>,
  FaRegCheckCircle: (props: IconBaseProps = {}) => <span><ReactIcons.FaRegCheckCircle {...props} /></span>,
  FaHeadset: (props: IconBaseProps = {}) => <span><ReactIcons.FaHeadset {...props} /></span>,
  FaArrowRight: (props: IconBaseProps = {}) => <span><ReactIcons.FaArrowRight {...props} /></span>,
  FaArrowLeft: (props: IconBaseProps = {}) => <span><ReactIcons.FaArrowLeft {...props} /></span>,
  FaTrash: (props: IconBaseProps = {}) => <span><ReactIcons.FaTrash {...props} /></span>,
  FaChevronLeft: (props: IconBaseProps = {}) => <span><ReactIcons.FaChevronLeft {...props} /></span>,
  FaChevronRight: (props: IconBaseProps = {}) => <span><ReactIcons.FaChevronRight {...props} /></span>,
  FaLaptop: (props: IconBaseProps = {}) => <span><ReactIcons.FaLaptop {...props} /></span>,
  FaTshirt: (props: IconBaseProps = {}) => <span><ReactIcons.FaTshirt {...props} /></span>,
  FaRunning: (props: IconBaseProps = {}) => <span><ReactIcons.FaRunning {...props} /></span>,
  FaHeartbeat: (props: IconBaseProps = {}) => <span><ReactIcons.FaHeartbeat {...props} /></span>,
  FaGamepad: (props: IconBaseProps = {}) => <span><ReactIcons.FaGamepad {...props} /></span>,
  FaDesktop: (props: IconBaseProps = {}) => <span><ReactIcons.FaDesktop {...props} /></span>,
  FaBook: (props: IconBaseProps = {}) => <span><ReactIcons.FaBook {...props} /></span>,
  FaKey: (props: IconBaseProps = {}) => <span><ReactIcons.FaKey {...props} /></span>,
  FaStore: (props: IconBaseProps = {}) => <span><ReactIcons.FaStore {...props} /></span>,
  
  // Add missing icons used in OrderDetailPage.tsx
  FaSync: (props: IconBaseProps = {}) => <span><ReactIcons.FaSync {...props} /></span>,
  FaBan: (props: IconBaseProps = {}) => <span><ReactIcons.FaBan {...props} /></span>,
  FaCalendarDay: (props: IconBaseProps = {}) => <span><ReactIcons.FaCalendarDay {...props} /></span>,
  FaQuestion: (props: IconBaseProps = {}) => <span><ReactIcons.FaQuestion {...props} /></span>,
  FaFileInvoice: (props: IconBaseProps = {}) => <span><ReactIcons.FaFileInvoice {...props} /></span>,
  
  // Add missing icons used in UserLayout.tsx
  FaTachometerAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaTachometerAlt {...props} /></span>,
  FaSignInAlt: (props: IconBaseProps = {}) => <span><ReactIcons.FaSignInAlt {...props} /></span>,
  FaFacebook: (props: IconBaseProps = {}) => <span><ReactIcons.FaFacebook {...props} /></span>,
  FaTwitter: (props: IconBaseProps = {}) => <span><ReactIcons.FaTwitter {...props} /></span>,
  FaInstagram: (props: IconBaseProps = {}) => <span><ReactIcons.FaInstagram {...props} /></span>,
  FaLinkedin: (props: IconBaseProps = {}) => <span><ReactIcons.FaLinkedin {...props} /></span>,
  FaPhone: (props: IconBaseProps = {}) => <span><ReactIcons.FaPhone {...props} /></span>,
  FaArrowUp: (props: IconBaseProps = {}) => <span><ReactIcons.FaArrowUp {...props} /></span>,
  
  // Add missing FaBolt icon used in FlashSales component
  FaBolt: (props: IconBaseProps = {}) => <span><ReactIcons.FaBolt {...props} /></span>,
  
  // Update spinner to handle style prop correctly
  FaSpinner: (props: IconBaseProps) => <span className="icon-spinner"><ReactIcons.FaSpinner {...props} /></span>,
};

// Export FiIcons for use in the app
export const FileIcons = {
  FiMoreVertical: (props: IconBaseProps) => <span><FiIcons.FiMoreVertical {...props} /></span>,
  FiToggleRight: (props: IconBaseProps) => <span><FiIcons.FiToggleRight {...props} /></span>,
  FiTrash2: (props: IconBaseProps) => <span><FiIcons.FiTrash2 {...props} /></span>,
  FiSearch: (props: IconBaseProps) => <span><FiIcons.FiSearch {...props} /></span>,
  FiPlus: (props: IconBaseProps) => <span><FiIcons.FiPlus {...props} /></span>,
}; 